name: Build and Deploy Jinja2 Site

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install jinja2

      - name: Render templates
        run: python render.py

      - name: Commit generated HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/

          if git diff --cached --quiet; then
            echo "No generated changes"
            exit 0
          fi

          git commit -m "Generate HTML"
          git push

    # uncomment for remote deploy
    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./docs
